const sideItem = {
    "addSide": [
        {
            "imgUrl": "img/side_img/french_fries.png",
            "name": "후렌치 후라이",
            "engName": "French Fries",
            "description": "통으로 썰어낸 감자를 맥도날드만의 노하우로 튀겨낸 남다른 맛과 바삭함! 맥도날드의 역사가 담긴 월드 클래스 후렌치 후라이",
            "setCost": 0,
            "cost": 3000,
        },
        {
            "imgUrl": "img/side_img/nuggets.png",
            "name": "맥너겟®",
            "engName": "McNuggets®",
            "description": "바삭하고 촉촉한 치킨이 한 입에 쏙! 다양한 소스로 입맛에 맞게 즐겨보세요!",
            "setCost": 400,
            "cost": 3400,
        },
        {
            "imgUrl": "img/side_img/tenders.png",
            "name": "맥스파이시®치킨 텐더",
            "engName": "McSpicy® Chicken Tenders",
            "description": "부드러운 100% 닭안심살을 스파이시 시즈닝으로 매콤 바삭하게 튀겨낸 치킨 텐더! 2가지 소스로 입맛에 맞게 즐겨보세요!",
            "setCost": 500,
            "cost": 3500,
        },
        {
            "imgUrl": "img/side_img/hash_brown.png",
            "name": "해쉬 브라운",
            "engName": "Hash Brown",
            "description": "씹으면 바삭바삭, 속은 부드러운 감자의 고소함.",
            "setCost": 0,
            "cost": 3000,
        },
        {
            "imgUrl": "img/side_img/golden_m_cheese_sticks.png",
            "name": "골든 모짜렐라 치즈스틱",
            "engName": "Golden Mozzarella Cheese Sticks",
            "description": "속이 꽉 찬 황금빛 바삭함! 자연 모짜렐라 치즈로 빈틈 없이 고소한 맥도날드 치즈스틱을 2조각과 4조각으로 다양하게 즐겨보세요!",
            "setCost": 300,
            "cost": 3300,
        },
        {
            "imgUrl": "img/side_img/tomato_chicken_snack_wrap.png",
            "name": "토마토 치킨 스낵랩",
            "engName": "Tomato Chicken Snack Wrap",
            "description": "상큼한 토마토와 바삭한 치킨의 조합! 매콤한 스파이시 어니언 소스로 더 맛있게!",
            "setCost": 800,
            "cost": 3800,
        },
        {
            "imgUrl": "img/side_img/shanghai_snack_wrap.png",
            "name": "상하이 치킨 스낵랩",
            "engName": "Shanghai Chicken Snack Wrap",
            "description": "매콤한 치킨에 달콤한 화이트 마요 소스로 매콤달콤하게! 베이컨에 양상추, 또띠아까지 어우러져 씹는 맛까지 즐겁다!",
            "setCost": 800,
            "cost": 3800,
        },
        {
            "imgUrl": "img/side_img/coleslaw.png",
            "name": "코울슬로",
            "engName": "Coleslaw",
            "description": "양배추, 당근, 양파가 상큼하고 크리미한 마요 드레싱과 어우러져 아삭하게 씹히는 샐러드",
            "setCost": 0,
            "cost": 2700,
        },
    ],
    
    "addDrink": [
        {
            "imgUrl": "img/drink_img/cola.png",
            "name": "코카-콜라",
            "engName": "Coca-Cola",
            "description": "갈증해소 뿐만이 아니라 기분까지 상쾌하게! 코카-콜라",
            "setCost": 0,
            "cost": 2400,
        },
        {
            "imgUrl": "img/drink_img/zero_cola.png",
            "name": "코카-콜라 제로",
            "engName": "Coca-Cola Zero",
            "description": "상쾌한 맛은 살리면서 웰빙 트렌드에 맞춰 설탕과 칼로리를 제로로 줄인 코카-콜라 제로",
            "setCost": 0,
            "cost": 2400,
        },
        {
            "imgUrl": "img/drink_img/sprite.png",
            "name": "스프라이트",
            "engName": "Sprite",
            "description": "청량함에 레몬, 라임향을 더한 시원함!",
            "setCost": 0,
            "cost": 2400,
        },
        {
            "imgUrl": "img/drink_img/fanta.png",
            "name": "환타",
            "engName": "Fanta",
            "description": "톡 쏘는 오렌지 향!",
            "setCost": 0,
            "cost": 2400,
        },
        {
            "imgUrl": "img/drink_img/vanilla_shake.png",
            "name": "바닐라 쉐이크 Medium",
            "engName": "Vanilla Shake Medium",
            "description": "신선한 우유에 달콤한 바닐라 시럽으로 맛을 더한 깔끔한 쉐이크!",
            "setCost": 1100,
            "cost": 3500,
        },
        {
            "imgUrl": "img/drink_img/strawberry_shake.png",
            "name": "딸기 쉐이크 Medium",
            "engName": "Strawberry Shake Medium",
            "description": "신선한 우유에 달콤한 딸기 시럽으로 맛을 더한 깔끔한 쉐이크!",
            "setCost": 1100,
            "cost": 3500,
        },
        {
            "imgUrl": "img/drink_img/choco_shake.png",
            "name": "초코 쉐이크 Medium",
            "engName": "Chocolate Shake Medium",
            "description": "신선한 우유에 달콤한 초코렛 시럽으로 맛을 더한 깔끔한 쉐이크!",
            "setCost": 1100,
            "cost": 3500,
        },
        {
            "imgUrl": "img/drink_img/orange_juice.png",
            "name": "오렌지 주스",
            "engName": "Orange Juice",
            "description": "비타민 C를 함유한 4년 연속 세계 판매 1위 100% 오렌지 주스.",
            "setCost": 0,
            "cost": 2400,
        },
        {
            "imgUrl": "img/drink_img/water.png",
            "name": "생수",
            "engName": "Mineral Water",
            "description": "활력을 되찾아주는 깔끔한 미네랄 생수.",
            "setCost": 0,
            "cost": 2000,
        },
        {
            "imgUrl": "img/drink_img/plum_peach_chiller.png",
            "name": "자투 천도복숭아 칠러",
            "engName": "Plum Peach Chiller",
            "description": "상콤한 자두와 달콤한 천도복숭아의 만남! 자두 천도복숭아 칠러",
            "setCost": 1300,
            "cost": 3700,
            "smallcost": 1900,
        },
        {
            "imgUrl": "img/drink_img/jeju_hallabong.png",
            "name": "제주 한라봉 칠러",
            "engName": "Jeju Hallabong Chiller",
            "description": "제주 한라봉의 상큼새콤한 맛과 향을 즐겨보세요!",
            "setCost": 1300,
            "cost": 3700,
            "smallcost": 1900,
        },
        {
            "imgUrl": "img/drink_img/vanilla_latte.png",
            "name": "바닐라 라떼",
            "engName": "Vanilla Latte",
            "description": "바로 내린 100% 친환경 커피의 진한 맛과 향, 1A등급 우유, 그리고 천연 바닐라 향으로 달콤함까지!",
            "setCost": 2100,
            "cost": 4500,
        },
        {
            "imgUrl": "img/drink_img/ice_vanilla_latte.png",
            "name": "아이스 바닐라 라떼",
            "engName": "Iced Vanilla Latte",
            "description": "바로 내린 100% 친환경 커피의 진한 맛과 향, 1A등급 우유, 그리고 천연 바닐라 향으로 달콤함까지!",
            "setCost": 2100,
            "cost": 4500,
        },
        {
            "imgUrl": "img/drink_img/cafe_latte.png",
            "name": "카페라떼",
            "engName": "Café Latte",
            "description": "바로 내린 100% 친환경 커피가 신선한 우유를 만나 더 신선하고 부드럽게!",
            "setCost": 1600,
            "cost": 4000,
        },
        {
            "imgUrl": "img/drink_img/Dcfn_latte.png",
            "name": "디카페인 카페라떼",
            "engName": "Decaffeine Café Latte",
            "description": "바로 내린 100% 친환경 커피가 신선한 우유를 만나 더 신선하고 부드럽게!",
            "setCost": 1800,
            "cost": 4200,
        },
        {
            "imgUrl": "img/drink_img/ice_latte.png",
            "name": "아이스 카페라떼",
            "engName": "Iced Café Latte",
            "description": "바로 내린 100% 친환경 커피가 신선한 우유를 만나 더 신선하고 부드럽게!",
            "setCost": 1600,
            "cost": 4000,
        },
        {
            "imgUrl": "img/drink_img/Dcfn_ice_latte.png",
            "name": "디카페인 아이스 카페라떼",
            "engName": "Decaffeine Iced Café Latte",
            "description": "바로 내린 100% 친환경 커피가 신선한 우유를 만나 더 신선하고 부드럽게!",
            "setCost": 1800,
            "cost": 4200,
        },
        {
            "imgUrl": "img/drink_img/americano.png",
            "name": "아메리카노",
            "engName": "Americano",
            "description": "바로 내린 100% 친환경 커피로 더 신선하게! 더 풍부하게!",
            "setCost": 900,
            "cost": 3300,
        },
        {
            "imgUrl": "img/drink_img/Dcfn_americano.png",
            "name": "디카페인 아메리카노",
            "engName": "Decaffeine Americano",
            "description": "바로 내린 100% 친환경 커피로 더 신선하게! 더 풍부하게!",
            "setCost": 1100,
            "cost": 3500,
        },
        {
            "imgUrl": "img/drink_img/ice_americano.png",
            "name": "아이스 아메리카노",
            "engName": "Iced Americano",
            "description": "바로 내린 100% 친환경 커피로 더 신선하게! 더 풍부하게!",
            "setCost": 900,
            "cost": 3300,
        },
        {
            "imgUrl": "img/drink_img/Dcfn_ice_americano.png",
            "name": "디카페인 아이스 아메리카노",
            "engName": "Decaffeine Iced Americano",
            "description": "바로 내린 100% 친환경 커피로 더 신선하게! 더 풍부하게!",
            "setCost": 1100,
            "cost": 3500,
        },
        {
            "imgUrl": "img/drink_img/cappuccino.png",
            "name": "카푸치노",
            "engName": "Cappuccino",
            "description": "바로 내린 100% 친환경 커피로 추출한 에스프레소 위에 갓 만든 우유 거품으로 더 부드럽게!",
            "setCost": 1600,
            "cost": 4000,
        },
        {
            "imgUrl": "img/drink_img/Dcfn_cappuccino.png",
            "name": "디카페인 카푸치노",
            "engName": "Decaffeine Cappuccino",
            "description": "바로 내린 100% 친환경 커피로 추출한 에스프레소 위에 갓 만든 우유 거품으로 더 부드럽게!",
            "setCost": 1800,
            "cost": 4200,
        },
        {
            "imgUrl": "img/drink_img/drip_coffee.png",
            "name": "드립 커피",
            "engName": "Drip Coffee",
            "description": "100% 아라비카 원두를 드립 커피의 부드러움으로 만나보세요.",
            "setCost": 300,
            "cost": 2700,
        },
        {
            "imgUrl": "img/drink_img/ice_drip_coffee.png",
            "name": "아이스 드립 커피",
            "engName": "Iced Drip Coffee",
            "description": "100% 아라비카 원두를 드립 커피의 부드러움으로 만나보세요.",
            "setCost": 300,
            "cost": 2700,
        },
    ],

    "addDessert": [
        {
            "imgUrl": "img/deesert_img/raspberry_pie.png",
            "name": "라즈베리 크림치즈 파이",
            "engName": "Raspberry Cream Cheese Pie",
            "description": "상큼한 라즈베리와 부드러운 크림치즈의 만남! 맥도날드 라즈베리 크림치즈 파이",
            "cost": 2200,
        },
        {
            "imgUrl": "img/deesert_img/very_strawberry_mcflurry.png",
            "name": "베리 스트로베리 맥플러리",
            "engName": "Very Strawberry McFlurry",
            "description": "신선한 1등급 원유에 국내산 딸기 과즙이 들어간 스트로베리 아이스크림에 오레오가 블랜드 되어 있는 맥플러리",
            "cost": 4000,
        },
        {
            "imgUrl": "img/deesert_img/oreo_mcflurry.png",
            "name": "오레오 맥플러리",
            "engName": "Oreo McFlurry",
            "description": "우유 듬뿍 신선한 아이스크림에 아삭아삭 오레오 쿠키가 가득!",
            "cost": 4000,
        },
        {
            "imgUrl": "img/deesert_img/strawberry_oreo_mcflurry.png",
            "name": "딸기 오레오 맥플러리",
            "engName": "Strawberry Oreo McFlurry",
            "description": "상큼한 딸기와 달콤한 오레오 쿠키가 신선한 우유 아이스크림에 퐁당!",
            "cost": 3300,
        },
        {
            "imgUrl": "img/deesert_img/choco_oreo_mcflurry.png",
            "name": "초코 오레오 맥플러리",
            "engName": "Choco Oreo McFlurry",
            "description": "초콜릿 퍼지와 오레오 쿠키까지! 달달함이 두 배로!",
            "cost": 3300,
        },
        {
            "imgUrl": "img/deesert_img/strawberry_cone.png",
            "name": "스트로베리콘",
            "engName": "Strawberry Cone",
            "description": "신선한 1등급 원유와 딸기과즙으로 만든 아이스크림",
            "cost": 1500,
        },
        {
            "imgUrl": "img/deesert_img/ice_cream_cone.png",
            "name": "아이스크림콘",
            "engName": "Ice Cream Cone",
            "description": "신선한 우유로 만든 부드러운 아이스크림 콘.",
            "cost": 1100,
        },
        {
            "imgUrl": "img/deesert_img/vanilla_sundae.png",
            "name": "바닐라 선데이 아이스크림",
            "engName": "Vanilla Sundae",
            "description": "신선한 우유로 만든 부드럽고 달콤한 아이스크림",
            "cost": 2100,
        },
        {
            "imgUrl": "img/deesert_img/choco_sundae.png",
            "name": "초코 선데이 아이스크림",
            "engName": "Chocolate Sundae",
            "description": "신선한 우유로 만든 아이스크림에 달콤한 초콜렛 시럽이 입안 가득.",
            "cost": 2100,
        },
        {
            "imgUrl": "img/deesert_img/strawberry_sundae.png",
            "name": "딸기 선데이 아이스크림",
            "engName": "Strawberry Sundae",
            "description": "신선한 우유와 딸기가 아이스크림으로 만났다!",
            "cost": 2100,
        },
        {
            "imgUrl": "img/deesert_img/oreo_affogato.png",
            "name": "오레오 아포가토",
            "engName": "Oreo Affogato",
            "description": "진한 에스프레소에 바닐라 아이스크림으로 달콤 쌉쌀하게, 오레오 쿠키로 바삭함까지!",
            "cost": 3800,
        },
    ],
}
